//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPV_Drone.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drone()
        {
            this.Drone_User = new HashSet<Drone_User>();
            this.Flight = new HashSet<Flight>();
        }
    
        public long id_drone { get; set; }
        public string name_model { get; set; }
        public long id_type_drone { get; set; }
        public Nullable<System.TimeSpan> time_flight { get; set; }
        public long id_type_control { get; set; }
        public Nullable<int> max_payload { get; set; }
        public string describe { get; set; }
    
        public virtual Control_Type Control_Type { get; set; }
        public virtual Type_Drone Type_Drone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drone_User> Drone_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
