//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPV_Drone.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drone_User
    {
        public long id_drone_user { get; set; }
        public long id_user { get; set; }
        public long id_drone { get; set; }
    
        public virtual Drone Drone { get; set; }
        public virtual Users Users { get; set; }
    }
}
