//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPV_Drone.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FPV_dronEntities1 : DbContext
    {
        public FPV_dronEntities1()
            : base("name=FPV_dronEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acsel> Acsel { get; set; }
        public virtual DbSet<Control_Type> Control_Type { get; set; }
        public virtual DbSet<Drone> Drone { get; set; }
        public virtual DbSet<Drone_User> Drone_User { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Drone> Type_Drone { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
